basePath: /
host: localhost:8080
info:
  contact: {}
  title: Phising Simulator API
  version: "0.1"
paths: {}
securityDefinitions:
  BearerAuth:
    description: Bearer 토큰 형식, Bearer {token}
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
